name:                sag
version:             0.1.0.0
github:              "sheepduke/sag"
license:             MIT
author:              "YUE Daian"
maintainer:          ""
copyright:           "2022 YUE Daian"

extra-source-files:
- README.org
- ChangeLog.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sheepduke/sag#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cmdargs
- containers
- file-embed
- text

library:
  source-dirs: src

executables:
  sag:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -prof
    # - -fprof-auto
    dependencies:
    - sag

tests:
  sag-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sag
